# Generated by Django 2.1.7 on 2019-04-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemPages', '0004_problems_solved'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='related_issues',
            field=models.ManyToManyField(to='ProblemPages.Problems'),
        ),
    ]
