# Generated by Django 2.1.7 on 2019-04-04 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProblemPages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='page_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
