# Generated by Django 2.1.7 on 2019-04-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemPages', '0002_problems_page_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
