# Generated by Django 2.1.7 on 2019-04-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemPages', '0003_problems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
