# Generated by Django 2.1.7 on 2019-06-18 21:22

import blog.utils.utility_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=blog.utils.utility_funcs.gen_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
